# Generated by Django 5.1.7 on 2025-08-10 04:10

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PracticeRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('练习', '练习'), ('模拟考试', '模拟考试'), ('正式考试', '正式考试')], default='练习', help_text='练习类型', max_length=10, verbose_name='类型')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, help_text='练习发生的时间', verbose_name='日期时间')),
                ('score', models.IntegerField(help_text='本次练习得分', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='得分')),
                ('duration_minutes', models.PositiveIntegerField(help_text='练习持续时间（分钟）', verbose_name='时长(分钟)')),
            ],
            options={
                'verbose_name': '练习记录',
                'verbose_name_plural': '练习记录',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('singleChoice', '单选题'), ('multipleChoice', '多选题'), ('judgment', '判断题'), ('shortAnswer', '简答题')], help_text='题目类型', max_length=20, verbose_name='类型')),
                ('difficulty', models.CharField(choices=[('easy', '简单'), ('medium', '中等'), ('hard', '困难')], help_text='题目难度级别', max_length=10, verbose_name='难度')),
                ('content', models.TextField(help_text='题目的文本内容', verbose_name='题目内容')),
                ('correct', models.BooleanField(help_text='用户是否答对', verbose_name='是否正确')),
                ('user_answer', models.JSONField(blank=True, help_text='用户的答案（JSON格式）', null=True, verbose_name='用户答案')),
                ('correct_answer', models.JSONField(help_text='题目的正确答案（JSON格式）', verbose_name='正确答案')),
                ('options', models.JSONField(blank=True, help_text='题目的选项（JSON格式）', null=True, verbose_name='选项')),
                ('analysis', models.TextField(blank=True, help_text='题目的解析说明', verbose_name='解析')),
            ],
            options={
                'verbose_name': '题目',
                'verbose_name_plural': '题目',
                'ordering': ['id'],
            },
        ),
    ]
