# Generated by Django 4.2.21 on 2025-12-12 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(
            'ALTER TABLE exercise_challenge DROP COLUMN `order`;',
            reverse_sql='ALTER TABLE exercise_challenge ADD COLUMN `order` INT DEFAULT 0;',
        ),
    ]
