# Generated by Django 5.1.7 on 2025-08-10 04:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('question', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='practicerecord',
            name='student',
            field=models.ForeignKey(help_text='关联的用户', on_delete=django.db.models.deletion.CASCADE, related_name='practice_records', to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AddField(
            model_name='question',
            name='record',
            field=models.ForeignKey(help_text='关联的练习记录', on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='question.practicerecord', verbose_name='练习记录'),
        ),
    ]
