# Generated by Django 4.2.21 on 2025-12-02 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("question", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Exercise",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "exercise_id",
                    models.CharField(
                        help_text="练习题的唯一标识符",
                        max_length=100,
                        unique=True,
                        verbose_name="练习题ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="练习题的名称",
                        max_length=200,
                        verbose_name="练习题名称",
                    ),
                ),
                (
                    "visits",
                    models.IntegerField(
                        default=0, help_text="练习题的访问次数", verbose_name="访问次数"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        help_text="练习题的状态",
                        max_length=50,
                        null=True,
                        verbose_name="状态",
                    ),
                ),
                (
                    "fork_from",
                    models.CharField(
                        blank=True,
                        help_text="从哪个练习题复刻而来",
                        max_length=100,
                        null=True,
                        verbose_name="来源练习题",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        help_text="练习题的创建时间", verbose_name="创建时间"
                    ),
                ),
                (
                    "publish_time",
                    models.DateTimeField(
                        blank=True,
                        help_text="练习题的发布时间",
                        null=True,
                        verbose_name="发布时间",
                    ),
                ),
            ],
            options={
                "verbose_name": "练习题",
                "verbose_name_plural": "练习题",
                "ordering": ["exercise_id"],
            },
        ),
        migrations.AddField(
            model_name="question",
            name="exercise",
            field=models.ForeignKey(
                blank=True,
                help_text="关联的练习题",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="questions",
                to="question.exercise",
                verbose_name="关联练习题",
            ),
        ),
    ]
