# Generated by Django 4.2.21 on 2025-12-12 08:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("question", "0003_exercise_question_exercise"),
    ]

    operations = [
        migrations.CreateModel(
            name="Challenge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "challenge_id",
                    models.CharField(
                        help_text="挑战题的唯一标识符",
                        max_length=100,
                        unique=True,
                        verbose_name="挑战题ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="题目的名称", max_length=200, verbose_name="题目名称"
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("singleChoice", "单选题"),
                            ("multipleChoice", "多选题"),
                            ("judgment", "判断题"),
                            ("shortAnswer", "简答题"),
                        ],
                        help_text="题目的类型（单选、多选、判断、简答等）",
                        max_length=20,
                        verbose_name="题目类型",
                    ),
                ),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("easy", "简单"),
                            ("medium", "中等"),
                            ("hard", "困难"),
                        ],
                        help_text="题目的难度级别",
                        max_length=10,
                        verbose_name="难度级别",
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        help_text="题目的文本内容", verbose_name="题目内容"
                    ),
                ),
                (
                    "answer",
                    models.TextField(help_text="题目的答案", verbose_name="答案"),
                ),
                (
                    "analysis",
                    models.TextField(
                        blank=True,
                        help_text="题目的解析说明",
                        null=True,
                        verbose_name="解析说明",
                    ),
                ),
                (
                    "is_multi",
                    models.BooleanField(
                        default=False,
                        help_text="是否为多选题",
                        verbose_name="是否为多选题",
                    ),
                ),
                (
                    "options",
                    models.TextField(
                        blank=True,
                        help_text="题目的选项（JSON格式）",
                        null=True,
                        verbose_name="选项",
                    ),
                ),
                (
                    "is_delete",
                    models.BooleanField(
                        default=False,
                        help_text="题目是否已删除",
                        verbose_name="是否删除",
                    ),
                ),
            ],
            options={
                "verbose_name": "挑战题",
                "verbose_name_plural": "挑战题",
                "ordering": ["challenge_id"],
            },
        ),
        migrations.CreateModel(
            name="ExerciseChallenge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "challenge",
                    models.ForeignKey(
                        help_text="关联的挑战题",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exercise_challenges",
                        to="question.challenge",
                        verbose_name="挑战题",
                    ),
                ),
                (
                    "exercise",
                    models.ForeignKey(
                        help_text="关联的练习题",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exercise_challenges",
                        to="question.exercise",
                        verbose_name="练习题",
                    ),
                ),
            ],
            options={
                "verbose_name": "练习题与挑战题关联",
                "verbose_name_plural": "练习题与挑战题关联",
                "db_table": "exercise_challenge",
                "unique_together": {("exercise", "challenge")},
            },
        ),
    ]
