# Generated by Django 4.2.21 on 2025-12-12 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("question", "0004_challenge_exercisechallenge"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="challenge",
            name="analysis",
        ),
        migrations.RemoveField(
            model_name="challenge",
            name="content",
        ),
        migrations.RemoveField(
            model_name="challenge",
            name="is_delete",
        ),
        migrations.RemoveField(
            model_name="challenge",
            name="is_multi",
        ),
        migrations.RemoveField(
            model_name="challenge",
            name="options",
        ),
        migrations.RemoveField(
            model_name="challenge",
            name="type",
        ),
        migrations.AddField(
            model_name="challenge",
            name="praises_count",
            field=models.IntegerField(
                default=0, help_text="题目点赞数", verbose_name="点赞数"
            ),
        ),
        migrations.AddField(
            model_name="challenge",
            name="score",
            field=models.IntegerField(
                default=0, help_text="题目分数", verbose_name="分数"
            ),
        ),
        migrations.AddField(
            model_name="challenge",
            name="task_pass",
            field=models.TextField(
                default="", help_text="题目的任务说明和内容", verbose_name="任务说明"
            ),
        ),
    ]
