# Generated by Django 5.2.4 on 2026-03-30 12:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "question",
            "0006_merge_0002_remove_order_from_exercisechallenge_0005_remove_challenge_analysis_remove_challenge_content_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="practicerecord",
            name="challenge",
            field=models.ForeignKey(
                blank=True,
                help_text="关联的挑战题",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="practice_records",
                to="question.challenge",
                verbose_name="挑战题",
            ),
        ),
    ]
