# Generated by Django 5.2.4 on 2026-03-30 15:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("question", "0007_practicerecord_challenge"),
    ]

    operations = [
        migrations.AlterField(
            model_name="practicerecord",
            name="score",
            field=models.IntegerField(
                help_text="本次练习得分",
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="得分",
            ),
        ),
    ]
