# Generated by Django 4.2.27 on 2026-02-09 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0003_alter_user_groups_alter_user_user_permissions"),
    ]

    operations = [
        # 由于我们已经使用原生SQL命令创建了role表并迁移了数据，
        # 这里只需要更新模型定义，不需要执行实际的数据库操作
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.IntegerField(
                help_text="区分用户类型：学生/教师/管理员",
                verbose_name="用户角色",
            ),
        ),
    ]
