# Generated by Django 4.2.27 on 2026-02-11 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0004_role_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Role",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "name",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="角色名称"
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="角色描述"
                    ),
                ),
            ],
            options={
                "verbose_name": "角色",
                "verbose_name_plural": "角色",
                "ordering": ["id"],
            },
        ),
        migrations.AlterField(
            model_name="user",
            name="password",
            field=models.CharField(max_length=128, verbose_name="密码"),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.IntegerField(
                help_text="区分用户类型：1=学生/2=教师/3=管理员",
                verbose_name="用户角色",
            ),
        ),
    ]
