# Generated by Django 5.2.7 on 2025-11-01 07:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('question', '0005_remove_challenge_analysis_remove_challenge_content_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('exercise', '习题相关'), ('announcement', '系统公告'), ('other', '其他通知')], default='exercise', help_text='对应前端type字段', max_length=20, verbose_name='通知类型')),
                ('title', models.CharField(help_text='对应前端title字段', max_length=200, verbose_name='通知标题')),
                ('content', models.TextField(help_text='对应前端content字段', verbose_name='通知内容')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='对应前端time字段（通知生成时间）', verbose_name='创建时间')),
                ('is_read', models.BooleanField(default=False, help_text='对应前端read字段（默认未读）', verbose_name='是否已读')),
                ('submission_time', models.DateTimeField(blank=True, help_text='对应前端details.submissionTime字段', null=True, verbose_name='学生提交时间')),
                ('exercise', models.ForeignKey(blank=True, help_text='details中的习题信息（如JavaScript高级特性）', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_notifications', to='question.exercise', verbose_name='关联习题')),
                ('practice_record', models.ForeignKey(blank=True, help_text='details中的答题数量（totalQuestions/attemptedQuestions）', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_notifications', to='question.practicerecord', verbose_name='关联练习记录')),
                ('recipient', models.ForeignKey(help_text='通知的接收者（必须是教师角色）', on_delete=django.db.models.deletion.CASCADE, related_name='received_notifications', to=settings.AUTH_USER_MODEL, verbose_name='接收教师')),
                ('student', models.ForeignKey(blank=True, help_text='details中的学生信息（如张明）', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_notifications', to=settings.AUTH_USER_MODEL, verbose_name='关联学生')),
            ],
            options={
                'verbose_name': '教师通知',
                'verbose_name_plural': '教师通知',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'is_read'], name='notificatio_recipie_dd6756_idx'), models.Index(fields=['recipient', 'type'], name='notificatio_recipie_f070f4_idx')],
            },
        ),
    ]
