# Generated by Django 5.1.7 on 2025-10-09 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClassInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='班级名称')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='班级编码')),
                ('course_name', models.CharField(max_length=100, verbose_name='课程名称')),
                ('create_time', models.DateField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '班级信息',
                'verbose_name_plural': '班级信息',
                'ordering': ['-create_time'],
            },
        ),
    ]
