# Generated by Django 5.2.7 on 2025-11-01 07:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classInfo', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeMastery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('knowledge_name', models.CharField(max_length=100, verbose_name='知识点名称')),
                ('mastery_type', models.CharField(choices=[('OVERALL', '整体掌握度'), ('EXCELLENT', '优秀学生掌握度')], max_length=20, verbose_name='掌握度类型')),
                ('mastery_value', models.IntegerField(help_text='0-100的整数', verbose_name='掌握度值')),
            ],
            options={
                'verbose_name': '知识点掌握度',
                'verbose_name_plural': '知识点掌握度',
                'unique_together': {('knowledge_name', 'mastery_type')},
            },
        ),
        migrations.CreateModel(
            name='ClassWeeklyProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.IntegerField(verbose_name='周次')),
                ('progress', models.IntegerField(verbose_name='班级进度')),
                ('class_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_progress', to='classInfo.classinfo', verbose_name='关联班级')),
            ],
            options={
                'verbose_name': '班级周进度',
                'verbose_name_plural': '班级周进度',
                'ordering': ['week'],
                'unique_together': {('class_info', 'week')},
            },
        ),
    ]
