# Generated by Django 5.1.7 on 2025-08-11 04:47

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('student_id', models.CharField(help_text='学生的唯一标识符', max_length=20, unique=True, verbose_name='学号')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='用户账户创建时间', verbose_name='创建时间')),
                ('user_avatar_url', models.URLField(blank=True, help_text='用户上传的头像图片URL', max_length=255, null=True, verbose_name='自定义头像URL')),
                ('user_avatar_emoji', models.CharField(default='👨\u200d💻', help_text='默认显示的emoji头像', max_length=10, verbose_name='默认头像emoji')),
                ('class_name', models.CharField(blank=True, help_text='如：计算机科学与技术 2023级', max_length=50, verbose_name='班级')),
                ('major', models.CharField(blank=True, help_text='如：计算机科学与技术', max_length=50, verbose_name='专业')),
                ('birth_date', models.DateField(blank=True, help_text='格式：YYYY-MM-DD', null=True, verbose_name='出生日期')),
                ('hometown', models.CharField(blank=True, help_text='如：广东省广州市', max_length=100, verbose_name='籍贯')),
                ('political_status', models.CharField(blank=True, help_text='如：团员、党员', max_length=20, verbose_name='政治面貌')),
                ('phone', models.CharField(blank=True, help_text='用户联系电话', max_length=20, verbose_name='手机号')),
                ('website', models.URLField(blank=True, help_text='个人博客或主页URL', max_length=255, null=True, verbose_name='个人网站')),
                ('bio', models.TextField(blank=True, help_text='用户的自我描述', verbose_name='个人简介')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
                'ordering': ['-created_at'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school', models.CharField(help_text='如：华南师范大学', max_length=100, verbose_name='学校名称')),
                ('period_s', models.DateField(help_text='入学日期，格式：YYYY-MM-DD', verbose_name='开始时间')),
                ('period_e', models.DateField(help_text='毕业日期，格式：YYYY-MM-DD', verbose_name='结束时间')),
                ('major', models.CharField(help_text='如：计算机科学与技术', max_length=50, verbose_name='专业')),
                ('degree', models.CharField(help_text='如：本科、硕士', max_length=20, verbose_name='学位')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education', to=settings.AUTH_USER_MODEL, verbose_name='关联用户')),
            ],
            options={
                'verbose_name': '教育经历',
                'verbose_name_plural': '教育经历',
                'ordering': ['-period_s'],
            },
        ),
        migrations.CreateModel(
            name='Hobby',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='如：编程、篮球', max_length=50, verbose_name='爱好名称')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hobbies', to=settings.AUTH_USER_MODEL, verbose_name='关联用户')),
            ],
            options={
                'verbose_name': '爱好',
                'verbose_name_plural': '爱好',
                'unique_together': {('user', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='如：JavaScript、Python', max_length=50, verbose_name='技能名称')),
                ('level', models.CharField(choices=[('初级', '初级'), ('中级', '中级'), ('高级', '高级')], help_text='技能掌握程度', max_length=10, verbose_name='技能水平')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to=settings.AUTH_USER_MODEL, verbose_name='关联用户')),
            ],
            options={
                'verbose_name': '技能',
                'verbose_name_plural': '技能',
                'unique_together': {('user', 'name')},
            },
        ),
    ]
