# Generated by Django 5.2.4 on 2026-02-07 04:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classInfo", "0003_knowledgemastery_classweeklyprogress"),
        ("student", "0002_alter_user_groups_alter_user_user_permissions"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="class_info",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="students",
                to="classInfo.classinfo",
                verbose_name="关联班级",
            ),
        ),
    ]
