# Generated by Django 4.2.27 on 2026-02-09 15:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("student", "0003_user_class_info"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={
                "ordering": ["student_id"],
                "verbose_name": "学生",
                "verbose_name_plural": "学生",
            },
        ),
        migrations.RemoveField(
            model_name="user",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="user",
            name="phone",
        ),
        migrations.RemoveField(
            model_name="user",
            name="user_avatar_emoji",
        ),
        migrations.RemoveField(
            model_name="user",
            name="user_avatar_url",
        ),
        migrations.AddField(
            model_name="user",
            name="core_user",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="student_user",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="education",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="education",
                to="student.user",
                verbose_name="关联学生",
            ),
        ),
        migrations.AlterField(
            model_name="hobby",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="hobbies",
                to="student.user",
                verbose_name="关联学生",
            ),
        ),
        migrations.AlterField(
            model_name="skill",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="skills",
                to="student.user",
                verbose_name="关联学生",
            ),
        ),
        migrations.AlterModelTable(
            name="education",
            table="student_education",
        ),
        migrations.AlterModelTable(
            name="hobby",
            table="student_hobby",
        ),
        migrations.AlterModelTable(
            name="skill",
            table="student_skill",
        ),
        migrations.AlterModelTable(
            name="user",
            table="student_user",
        ),
    ]
