# Generated by Django 5.1.7 on 2025-08-11 04:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgePoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='如：变量与数据类型', max_length=100, verbose_name='知识点名称')),
                ('category', models.CharField(choices=[('core', '核心知识点'), ('basic', '基础知识点'), ('advanced', '高级知识点'), ('extended', '扩展知识点')], help_text='如：core/basic', max_length=20, verbose_name='分类标识')),
                ('mastery', models.IntegerField(help_text='掌握百分比（0-100）', verbose_name='掌握程度')),
                ('description', models.TextField(help_text='对知识点的说明', verbose_name='知识点描述')),
                ('practice_count', models.IntegerField(default=0, help_text='该知识点的练习次数', verbose_name='练习次数')),
                ('last_practiced', models.DateField(blank=True, help_text='最后一次练习的日期', null=True, verbose_name='最后练习时间')),
                ('user', models.ForeignKey(help_text='关联的用户', on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_points', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '知识点',
                'verbose_name_plural': '知识点',
                'ordering': ['id'],
            },
        ),
    ]
