# Generated by Django 5.2.4 on 2025-11-08 09:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("knowledge", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="knowledgepoint",
            name="user",
            field=models.ForeignKey(
                help_text="关联的用户",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_knowledge_points",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
