# Generated by Django 5.2.4 on 2025-12-10 12:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("knowledge", "0002_alter_knowledgepoint_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="Chapter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="如：Python基础语法",
                        max_length=200,
                        verbose_name="章节名称",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="对章节的详细说明",
                        null=True,
                        verbose_name="章节描述",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        help_text="章节创建时间", verbose_name="创建时间"
                    ),
                ),
            ],
            options={
                "verbose_name": "章节",
                "verbose_name_plural": "章节",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="如：Python编程入门",
                        max_length=200,
                        verbose_name="课程名称",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="对课程的详细说明", verbose_name="课程描述"
                    ),
                ),
                (
                    "learning_notes",
                    models.TextField(
                        blank=True,
                        help_text="课程学习提示",
                        null=True,
                        verbose_name="学习笔记",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        help_text="课程创建时间", verbose_name="创建时间"
                    ),
                ),
                (
                    "publish_time",
                    models.DateTimeField(
                        help_text="课程发布时间", verbose_name="发布时间"
                    ),
                ),
                (
                    "visits",
                    models.IntegerField(
                        default=0, help_text="课程访问次数", verbose_name="访问量"
                    ),
                ),
            ],
            options={
                "verbose_name": "课程",
                "verbose_name_plural": "课程",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="CourseChapter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "position",
                    models.FloatField(
                        help_text="章节在课程中的顺序", verbose_name="章节顺序"
                    ),
                ),
                (
                    "chapter",
                    models.ForeignKey(
                        help_text="关联的章节",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chapter_courses",
                        to="knowledge.chapter",
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        help_text="关联的课程",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="course_chapters",
                        to="knowledge.course",
                    ),
                ),
            ],
            options={
                "verbose_name": "课程-章节关系",
                "verbose_name_plural": "课程-章节关系",
                "ordering": ["course", "position"],
                "unique_together": {("course", "chapter")},
            },
        ),
    ]
