# Generated by Django 4.2.21 on 2025-12-10 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("knowledge", "0003_chapter_course_coursechapter"),
    ]

    operations = [
        migrations.CreateModel(
            name="KnowledgeTopics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "topic_id",
                    models.IntegerField(
                        help_text="数据集中topics表的topic_id",
                        unique=True,
                        verbose_name="Topics表ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="知识点的中文名称",
                        max_length=100,
                        verbose_name="知识点名称",
                    ),
                ),
                (
                    "clean_name",
                    models.CharField(
                        blank=True,
                        help_text="解决编码问题后的中文名称",
                        max_length=100,
                        null=True,
                        verbose_name="清洗后名称",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("core", "核心知识点"),
                            ("basic", "基础知识点"),
                            ("advanced", "高级知识点"),
                            ("extended", "扩展知识点"),
                        ],
                        help_text="知识点分类",
                        max_length=20,
                        null=True,
                        verbose_name="知识点分类",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="对知识点的详细说明",
                        null=True,
                        verbose_name="知识点描述",
                    ),
                ),
            ],
            options={
                "verbose_name": "公共知识点",
                "verbose_name_plural": "公共知识点",
                "db_table": "knowledge_topics",
                "ordering": ["topic_id"],
            },
        ),
    ]
