# Generated by Django 4.2.21 on 2025-12-12 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("question", "0004_challenge_exercisechallenge"),
        ("knowledge", "0004_knowledgetopics"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="coursechapter",
            table="course_chapter",
        ),
        migrations.CreateModel(
            name="KnowledgeChallengeTopic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="记录创建时间",
                        verbose_name="创建时间",
                    ),
                ),
                (
                    "challenge",
                    models.ForeignKey(
                        blank=True,
                        help_text="关联的挑战题",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="topic_relations",
                        to="question.challenge",
                        verbose_name="挑战题",
                    ),
                ),
                (
                    "topic",
                    models.ForeignKey(
                        help_text="关联的知识点",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="challenge_relations",
                        to="knowledge.knowledgetopics",
                    ),
                ),
            ],
            options={
                "verbose_name": "知识点与题目关联",
                "verbose_name_plural": "知识点与题目关联",
                "db_table": "challenge_topic",
                "ordering": ["topic", "challenge"],
                "unique_together": {("topic", "challenge")},
            },
        ),
        migrations.CreateModel(
            name="CourseExercise",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "position",
                    models.IntegerField(
                        help_text="练习题在课程中的位置顺序", verbose_name="练习题顺序"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="记录创建时间",
                        verbose_name="创建时间",
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        help_text="关联的课程",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="course_exercises",
                        to="knowledge.course",
                    ),
                ),
                (
                    "exercise",
                    models.ForeignKey(
                        help_text="关联的练习题",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exercise_courses",
                        to="question.exercise",
                    ),
                ),
            ],
            options={
                "verbose_name": "课程与练习题关联",
                "verbose_name_plural": "课程与练习题关联",
                "db_table": "course_exercise",
                "ordering": ["course", "position"],
                "unique_together": {("course", "exercise")},
            },
        ),
    ]
