# Generated by Django 4.2.21 on 2025-12-12 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0005_alter_coursechapter_table_knowledgechallengetopic_and_more'),
    ]
    operations = [
        migrations.RunSQL(
            'ALTER TABLE challenge_topic DROP COLUMN `order`;',
            reverse_sql='ALTER TABLE challenge_topic ADD COLUMN `order` INT DEFAULT 0;',
        ),
        migrations.RunSQL(
            'ALTER TABLE challenge_topic DROP COLUMN `is_delete`;',
            reverse_sql='ALTER TABLE challenge_topic ADD COLUMN `is_delete` TINYINT(1) DEFAULT 0;',
        ),
    ]
