# Generated by Django 5.2.4 on 2026-02-14 10:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("knowledge", "0006_remove_order_is_delete_from_knowledgechallengetopic"),
        ("teacher", "0004_teacher_email_teacher_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chapter",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, help_text="章节创建时间", verbose_name="创建时间"
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, help_text="课程创建时间", verbose_name="创建时间"
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="publish_time",
            field=models.DateTimeField(
                auto_now_add=True, help_text="课程发布时间", verbose_name="发布时间"
            ),
        ),
        migrations.CreateModel(
            name="CourseTeacher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="记录创建时间",
                        verbose_name="创建时间",
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        help_text="关联的课程",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="course_teachers",
                        to="knowledge.course",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        help_text="关联的老师",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="teacher_courses",
                        to="teacher.teacher",
                    ),
                ),
            ],
            options={
                "verbose_name": "课程与老师关联",
                "verbose_name_plural": "课程与老师关联",
                "db_table": "course_teacher",
                "ordering": ["course", "teacher"],
                "unique_together": {("course", "teacher")},
            },
        ),
    ]
