# Generated by Django 5.2.4 on 2026-02-14 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("knowledge", "0007_alter_chapter_created_at_alter_course_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="对课程的详细说明",
                null=True,
                verbose_name="课程描述",
            ),
        ),
    ]
