# Generated by Django 5.2.7 on 2025-12-21 02:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GraphDomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='领域名称')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_graph_domains', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '知识图谱领域',
                'verbose_name_plural': '知识图谱领域',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='KnowledgeGraph',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='图谱名称')),
                ('type', models.CharField(choices=[('concept', '概念图谱'), ('relationship', '关系图谱'), ('hierarchical', '层级图谱'), ('integrated', '综合图谱')], default='concept', max_length=20, verbose_name='图谱类型')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('published', '已发布'), ('archived', '已归档')], default='draft', max_length=20, verbose_name='状态')),
                ('description', models.TextField(blank=True, default='', verbose_name='描述')),
                ('tags', models.JSONField(blank=True, default=list, verbose_name='标签')),
                ('content', models.JSONField(blank=True, default=dict, verbose_name='图谱内容')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='发布时间')),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='graphs', to='graphs.graphdomain', verbose_name='知识领域')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_graphs', to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
            ],
            options={
                'verbose_name': '知识图谱',
                'verbose_name_plural': '知识图谱',
                'ordering': ['-updated_at', '-id'],
            },
        ),
    ]
