# Generated by Django 4.2.27 on 2026-02-15 08:50

from django.db import migrations


def add_default_domains(apps, schema_editor):
    GraphDomain = apps.get_model('graphs', 'GraphDomain')
    
    # 基于knowledge_structure_response.json文件分析出的编程相关知识领域
    domains = [
        'C/C++ 编程',
        'Python 编程',
        'Web 前端开发',
        '数据结构与算法',
        '机器学习',
        '数据库技术',
        '云计算与容器',
        '移动应用开发',
        '测试技术',
        '其他编程技术'
    ]
    
    for domain_name in domains:
        # 检查是否已存在，避免重复添加
        if not GraphDomain.objects.filter(name=domain_name).exists():
            GraphDomain.objects.create(name=domain_name)


def remove_default_domains(apps, schema_editor):
    GraphDomain = apps.get_model('graphs', 'GraphDomain')
    
    domains = [
        'C/C++ 编程',
        'Python 编程',
        'Web 前端开发',
        '数据结构与算法',
        '机器学习',
        '数据库技术',
        '云计算与容器',
        '移动应用开发',
        '测试技术',
        '其他编程技术'
    ]
    
    GraphDomain.objects.filter(name__in=domains).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('graphs', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_default_domains, remove_default_domains),
    ]