# Generated by Django 4.2.27 on 2026-04-03 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("teacher", "0004_teacher_email_teacher_name"),
        ("graphs", "0002_add_default_domains"),
    ]

    operations = [
        migrations.AlterField(
            model_name="graphdomain",
            name="created_by",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="创建者"
            ),
        ),
        migrations.AlterField(
            model_name="knowledgegraph",
            name="owner",
            field=models.ForeignKey(
                db_column="owner_id",
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="owned_graphs",
                to="teacher.teacher",
                to_field="teacher_id",
                verbose_name="创建者",
            ),
        ),
    ]
