# Generated by Django 5.1.7 on 2025-08-12 01:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('student', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserStatistics',
            fields=[
                ('user', models.ForeignKey(help_text='关联的用户', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='statistics', serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
                ('total_attempts', models.PositiveIntegerField(default=0, help_text='用户的总练习次数', verbose_name='总练习次数')),
                ('avg_score', models.DecimalField(decimal_places=2, default=0.0, help_text='用户的平均得分', max_digits=5, verbose_name='平均得分')),
                ('total_duration_minutes', models.PositiveIntegerField(default=0, help_text='用户的总练习时长（分钟）', verbose_name='总时长(分钟)')),
                ('highest_score', models.PositiveIntegerField(default=0, help_text='用户的最高得分', verbose_name='最高得分')),
                ('last_highest_date', models.DateField(blank=True, help_text='用户最近一次获得最高分的日期', null=True, verbose_name='最高分日期')),
                ('type_accuracy', models.JSONField(blank=True, help_text='各题型的正确率（JSON格式）', null=True, verbose_name='题型正确率')),
                ('difficulty_accuracy', models.JSONField(blank=True, help_text='各难度题目的正确率（JSON格式）', null=True, verbose_name='难度正确率')),
                ('last_updated', models.DateTimeField(auto_now=True, help_text='统计数据的最后更新时间', verbose_name='最后更新时间')),
            ],
            options={
                'verbose_name': '用户统计',
                'verbose_name_plural': '用户统计',
            },
        ),
        migrations.CreateModel(
            name='HistoryRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('练习', '练习'), ('考试', '考试')], max_length=10)),
                ('date', models.DateTimeField()),
                ('score', models.IntegerField()),
                ('duration', models.CharField(max_length=20)),
                ('expanded', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_records', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
