# Generated by Django 5.2.4 on 2025-11-08 14:00

from django.db import migrations, models
from django.conf import settings
from django.db.models.fields.related import OneToOneField


class Migration(migrations.Migration):

    dependencies = [
        ("historyRecord", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstatistics',
            name='user',
            field=OneToOneField(
                on_delete=models.CASCADE,
                related_name='knowledge_points',
                to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
