# Generated by Django 5.2.4 on 2025-11-08 14:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("historyRecord", "0002_auto_20251108_2200"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="userstatistics",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="userstatistics",
            name="user",
            field=models.OneToOneField(
                help_text="关联的用户",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="statistics",
                to=settings.AUTH_USER_MODEL,
                verbose_name="用户",
            ),
        ),
    ]
