# Generated by Django 4.2.21 on 2025-12-07 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("historyRecord", "0003_userstatistics_id_alter_userstatistics_user"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="historyrecord",
            index=models.Index(
                fields=["user", "type", "date"], name="idx_user_type_date"
            ),
        ),
    ]
