# Generated by Django 5.2.4 on 2026-03-30 12:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("historyRecord", "0004_add_unique_index_to_historyrecord"),
        ("question", "0007_practicerecord_challenge"),
    ]

    operations = [
        migrations.AddField(
            model_name="historyrecord",
            name="challenge",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="history_records",
                to="question.challenge",
                verbose_name="挑战题",
            ),
        ),
    ]
