"""
Django settings for ITS_project project.

Generated by 'django-admin startproject' using Django 5.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""
from idlelib import history
from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-6o_fa3n-har18%o9aiew9#uev983o@ld(1f*#$l!ybu8laz(p3'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['localhost', '127.0.0.1']


# Application definition
# settings.py
AUTH_USER_MODEL = 'user.User'  # 格式：应用名.模型名

INSTALLED_APPS = [
    'corsheaders',
    'rest_framework',
    'rest_framework.authtoken',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'student',
    'question',
    'historyRecord',
    'knowledge',
    'visualization',
    'teacher',
    'classInfo',
    'notification',
    'user',
    'graphs'
]

REST_FRAMEWORK = {
    # 分页配置：匹配前端pageSize=10
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 10,

    # 权限配置：需登录才能访问接口，临时禁用以测试接口
    # 'DEFAULT_PERMISSION_CLASSES': [
    #     'rest_framework.permissions.IsAuthenticated',
    # ],

    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ],
}

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',  
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'ITS_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'ITS_project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'igs_db',
        'USER': 'root',
        'PASSWORD': '123456',
        'HOST': 'localhost',
        'PORT': '3306',
        'OPTIONS': {
            'charset': 'utf8mb4',
            'init_command': "SET sql_mode='STRICT_TRANS_TABLES'"
        }
    }
}


# 设置语言代码为zh-hans，默认为en-us
LANGUAGE_CODE = 'zh-hans'
# 设置时区为亚洲上海，默认是UTC
TIME_ZONE = 'Asia/Shanghai'
# 时区感知
USE_TZ = True


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'



# settings.py
CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",  # Vue3开发环境默认端口
    "http://127.0.0.1:5173",
    "http://localhost:5174",  # 可能的备用端口
    "http://127.0.0.1:5174",
    "http://localhost:5175",  # 备用端口
    "http://127.0.0.1:5175",
    "http://localhost:5176",  # 当前运行的端口
    "http://127.0.0.1:5176",
    "http://localhost:3000",  # 常见的React端口
    "http://127.0.0.1:3000",
    "http://localhost:8080",  # 常见的Vue 2端口
    "http://127.0.0.1:8080",
]
CORS_ALLOW_CREDENTIALS = True  # 允许跨域请求携带Cookie
CORS_ALLOW_METHODS = ["GET", "POST", "PUT", "PATCH", "DELETE", "OPTIONS"]  # 允许的HTTP方法
CORS_ALLOW_HEADERS = ["*"]  # 允许所有请求头


# 1. 项目根目录（自动获取，无需修改）
BASE_DIR = Path(__file__).resolve().parent.parent

# 2. 静态资源基础配置（原有配置保留，新增/修改 MEDIA 配置）
STATIC_URL = '/static/'  # 静态资源访问URL前缀（如 http://localhost:8000/static/）
# 开发环境下静态文件目录（若已有，保留）
STATICFILES_DIRS = [
    # os.path.join(BASE_DIR, 'static'),  # 指向项目根目录下的 static 文件夹
]

# 3. 将用户上传文件（头像）存储到/avatars
MEDIA_URL = '/avatars/'  # 头像访问URL前缀（如 http://localhost:8000/avatars/）
MEDIA_ROOT = os.path.join(BASE_DIR,  'avatars')  # 本地存储路径：项目根目录/static/avatars


# Neo4j 数据库配置
NEO4J_URI = 'bolt://localhost:7687'
NEO4J_USER = 'neo4j'
NEO4J_PASSWORD = 'password'  # 请根据实际情况修改密码