# Generated by Django 5.1.7 on 2025-08-12 01:08

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(help_text='如：Python编程基础', max_length=100, verbose_name='课程名称')),
                ('is_completed', models.BooleanField(default=False, help_text='标记课程是否已完成', verbose_name='是否完成')),
                ('score', models.IntegerField(default=0, help_text='课程得分（0-100）', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='课程成绩')),
                ('last_studied', models.DateTimeField(auto_now=True, help_text='最后一次学习该课程的时间', verbose_name='最后学习时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_progresses', to=settings.AUTH_USER_MODEL, verbose_name='关联用户')),
            ],
            options={
                'verbose_name': '课程进度',
                'verbose_name_plural': '课程进度',
                'unique_together': {('user', 'course_name')},
            },
        ),
        migrations.CreateModel(
            name='ProgrammingSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='如：JavaScript、Python', max_length=50, verbose_name='技能名称')),
                ('icon', models.CharField(help_text='技能对应的emoji图标，如⚡、🐍', max_length=10, verbose_name='技能图标（emoji）')),
                ('level', models.IntegerField(help_text='技能掌握程度（0-100）', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='技能水平')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programming_skills', to=settings.AUTH_USER_MODEL, verbose_name='关联用户')),
            ],
            options={
                'verbose_name': '编程技能',
                'verbose_name_plural': '编程技能',
                'unique_together': {('user', 'name')},
            },
        ),
    ]
