# Generated by Django 5.1.7 on 2025-10-09 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_id', models.CharField(help_text='教师唯一标识', max_length=20, unique=True, verbose_name='工号')),
                ('title', models.CharField(help_text='如：教授、讲师', max_length=50, verbose_name='职称')),
                ('department', models.CharField(help_text='如：计算机学院', max_length=100, verbose_name='所属院系')),
                ('office_address', models.CharField(blank=True, max_length=200, null=True, verbose_name='办公室地址')),
            ],
            options={
                'verbose_name': '教师档案',
                'verbose_name_plural': '教师档案',
                'ordering': ['teacher_id'],
            },
        ),
    ]
