# Generated by Django 5.2.7 on 2025-11-01 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='如：Web前端开发、算法与数据结构', max_length=100, unique=True, verbose_name='科目名称')),
                ('description', models.TextField(blank=True, null=True, verbose_name='科目描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '教学科目',
                'verbose_name_plural': '教学科目',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='teacher',
            name='bio',
            field=models.TextField(blank=True, null=True, verbose_name='个人简介'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='出生日期'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='hometown',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='籍贯'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='political_status',
            field=models.CharField(blank=True, choices=[('群众', '群众'), ('党员', '党员'), ('团员', '团员'), ('其他', '其他')], max_length=50, null=True, verbose_name='政治面貌'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='subjects',
            field=models.ManyToManyField(blank=True, related_name='teachers', to='teacher.subject', verbose_name='教学科目'),
        ),
    ]
