# Generated by Django 4.2.27 on 2026-02-11 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teacher", "0003_subject_teacher_bio_teacher_birth_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="teacher",
            name="email",
            field=models.EmailField(
                blank=True, max_length=254, null=True, verbose_name="邮箱"
            ),
        ),
        migrations.AddField(
            model_name="teacher",
            name="name",
            field=models.CharField(
                blank=True, max_length=150, null=True, verbose_name="姓名"
            ),
        ),
    ]
